version: '3.1'

services:
  php:
    build:
      labels:
      - "traefik.enable=false"
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    restart: unless-stopped
    ports:
      - 9999:80
    depends_on:
    - phpmyadmin
    - phpdb

  phpdb:
    labels:
    - "traefik.enable=false"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./my.cnf:/etc/my.cnf:ro

  phpmyadmin:
      labels:
      - "traefik.enable=false"
      image: phpmyadmin
      restart: unless-stopped
      depends_on:
      - phpdb
      ports:
      - 9998:80
      environment:
        - PMA_HOST=phpdb
        - PMA_USER=root
        - PMA_PASSWORD=root
        - PMA_PMADB=phpmyadmin
